In [10]:

import matplotlib.pyplot as plt
import csv
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#Carga dos dados de Treino
entrada =[]
saidaDesejada = []

print("Printando os dados das Plantas Iris para Treino")
with open('DadosDeTreino.csv') as csvfile:
  dados = csv.reader(csvfile)
  for linha in dados:
    print(linha)
    coluna = linha[0].split(',')
    entrada.append([float(coluna[0]),float(coluna[3])])
    saidaDesejada.append(coluna[4].replace('"',''))

print("Quantidade de dados: ", len(entrada))
for ind in range(0,len(entrada)):
  print("Features de entrada: ", entrada[ind],"-", "Classe: " + saidaDesejada[ind])

csvfile.close()

Printando os dados das Plantas Iris para Treino
['1.9', '45', '77', '21.32963989', 'Normal', '']


IndexError: list index out of range

In [4]:
#Treinamento 
#clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
print('Treinando...')
#model = MLPClassifier()  #com hiperametros default, para ver quais são consulte https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
#model = MLPClassifier(verbose=True)  #Exibindo o treinamento, onde iteração é a época e loss é o erro quadrado médio
#'''
model = MLPClassifier(
    hidden_layer_sizes=(20,),
    max_iter=300,
    verbose=True,
    learning_rate='constant',
    learning_rate_init=0.01,
    activation='relu',
    solver = 'adam'
)
#'''

model.fit(entrada,saidaDesejada)


Treinando...
Iteration 1, loss = 2.08856259
Iteration 2, loss = 1.90734571
Iteration 3, loss = 1.74173211
Iteration 4, loss = 1.58845136
Iteration 5, loss = 1.44889120
Iteration 6, loss = 1.32146674
Iteration 7, loss = 1.20599215
Iteration 8, loss = 1.10382071
Iteration 9, loss = 1.01708877
Iteration 10, loss = 0.94660278
Iteration 11, loss = 0.89271577
Iteration 12, loss = 0.85541368
Iteration 13, loss = 0.83367796
Iteration 14, loss = 0.82462837
Iteration 15, loss = 0.82310887
Iteration 16, loss = 0.82357424
Iteration 17, loss = 0.82120410
Iteration 18, loss = 0.81291251
Iteration 19, loss = 0.79809569
Iteration 20, loss = 0.77690408
Iteration 21, loss = 0.75076306
Iteration 22, loss = 0.72155020
Iteration 23, loss = 0.69108190
Iteration 24, loss = 0.66134130
Iteration 25, loss = 0.63449489
Iteration 26, loss = 0.61257059
Iteration 27, loss = 0.59509972
Iteration 28, loss = 0.58097775
Iteration 29, loss = 0.56939197
Iteration 30, loss = 0.55930257
Iteration 31, loss = 0.54948971
Iter

MLPClassifier(hidden_layer_sizes=(20,), learning_rate_init=0.01, max_iter=300,
              verbose=True)

In [15]:
#Carga dos dados de Teste
entrada =[]
saidaDesejada = []

print("Printando os dados das Plantas Iris para Teste")
with open('DadosDeTeste.csv') as csvfile:
  dados = csv.reader(csvfile)
  for linha in dados:
    print(linha)
    coluna = linha.split(',')
    print (coluna[0])
    print (coluna[0])
    print (coluna[1])
    print (coluna[2])
    print (coluna[3])
    entrada.append([float(coluna[0]),float(coluna[3])])
    saidaDesejada.append(coluna[4].replace('"',''))

print("Quantidade de dados: ", len(entrada))
for ind in range(0,len(entrada)):
  print("Features de entrada: ", entrada[ind],"-", "Classe: " + saidaDesejada[ind])

csvfile.close()

Printando os dados das Plantas Iris para Teste
['1.65', '20', '115', '42.2', 'Obesidade Morbida']


AttributeError: 'list' object has no attribute 'split'

In [6]:
#Generalização - Teste com Y
print('Testando...')

saidaPredita = model.predict(entrada)
print('Predição: ', saidaPredita)

print(model.predict_proba(entrada))
#print(model.score(entrada,saidaDesejada,sample_weight=None))

mat = confusion_matrix(saidaDesejada, saidaPredita)
print(mat)
accuracy_score(saidaDesejada, saidaPredita)



Testando...
Predição:  ['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica'
 'Virginica' 'Virginica' 'Virginica' 'Virginica' 'Virginica']
[[9.99683502e-01 3.16498187e-04 6.80873861e-19]
 [9.98731307e-01 1.26869311e-03 4.31924845e-17]
 [9.99474754e-01 5.25246297e-04 9.21970736e-18]
 [9.98691031e-01 1.30896919e-03 1.68177199e-16]
 [9.99761225e-01 2.38775304e-04 4.99557056e-19]
 [9.99335300e-01 6.64699760e-04 3.40396207e-18]
 [9.99355576e-01 6.44423961e-04 3.28733155e-17]
 [9.99426305e-01 5.73694924e-04 4.92449853e-18]
 [9.98347406e-01 1.65259449e-03 5.47622373e-16]
 [9.99154946e-01 8.45053721e-04 1.44852877e-17]
 [4.28061911e-04 9.99396199e-01 1.75739238e-04]
 [5.55921679e-04 9.98218513e-01 1.22556499e-03]
 [2.73631279e-04 9.95449156e-01 4.27721318e-03]
 [1.289

1.0